### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by insperatum** [pnlng/bartime#8]
Just cloned and ran `node dist/server.js` but I get this error:

<img width="639" alt="CleanShot 2021-07-04 at 10 09 42@2x" src="https://user-images.githubusercontent.com/3738275/124388236-06b7dd80-dcb0-11eb-8246-401e359b9ced.png">

Any ideas why?

**Comment by pnlng** [comment]
There was a bug. If you clone the repo again and run `make serve`, it should be fixed!
